root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler403, handler500

from django.views.static import serve

from root.settings import MEDIA_ROOT, STATIC_ROOT
from src.core.views import handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.urls')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" HANDLERS FOR 404 AND 500 ERRORS -------------------------------------------------------------------------------- """
handler404 = handler404
handler403 = handler403
handler500 = handler500

src/services/assets/urls.py
from django.urls import path

from .views import (
    IndexView,
    AccountBalanceUpdateView,
    AccountBalanceList,
    AccountBalanceCreateView,
    CashInHandDetailView,
    AddCashInHandView,
    AccountBalanceDetailView,
    AddAccountBalanceView,
    AccountBalanceDeleteView, AccountBalanceTransferView
)

app_name = "assets"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("accounts/", AccountBalanceList.as_view(), name="accounts"),
    path(
        "accounts/create/", AccountBalanceCreateView.as_view(), name="accounts_create"
    ),
    path(
        "account/<str:pk>/update/",
        AccountBalanceUpdateView.as_view(),
        name="account_balance_update",
    ),
    path(
        "account/<str:pk>/detail/",
        AccountBalanceDetailView.as_view(),
        name="account-detail",
    ),
    path(
        "account/<str:pk>/add-balance/",
        AddAccountBalanceView.as_view(),
        name="add-balance",
    ),
    path("cash-in-hand/add/", AddCashInHandView.as_view(), name="add-cash-in-hand"),
    path("cash-in-hand/", CashInHandDetailView.as_view(), name="cash_list"),

    path('delete/<str:pk>/', AccountBalanceDeleteView.as_view(), name='account_balance_delete'),
    path('transfer/<str:pk>/', AccountBalanceTransferView.as_view(), name='transfer'),
]

src/services/charts/urls.py
from django.urls import path
from .views import (
    ChartsIndex,
    generate_project_report,
    generate_bank_statements_view,
    project_expenses,
    yearly_report
)

app_name = "charts"

urlpatterns = [
    path("", ChartsIndex.as_view(), name="list"),
    path("project-report/<str:pk>/", generate_project_report, name="project-report"),
    path(
        "project-expense-sheet/<str:pk>/",
        project_expenses,
        name="project-expense-journal",
    ),
    path(
        "generate-bank-statements/",
        generate_bank_statements_view,
        name="generate_bank_statements",
    ),
    path('yearly-report/', yearly_report, name='yearly_report'),
]

src/services/invoice/urls.py
from django.urls import path
from .views import (
    CreateInvoiceView,
    InvoiceDetailView,
    InvoicePaidView,
    InvoiceDeleteView,
    InvoiceUpdateView,
    UpdateInvoiceView, DeliveryChallanView, DeleteDeliveryChallanView,
)

app_name = "invoice"

urlpatterns = [
    path(
        "project/<str:pk>/create-invoice/", CreateInvoiceView.as_view(), name="create"
    ),
    path("detail/<str:pk>/", InvoiceDetailView.as_view(), name="detail"),
    path("paid/<str:pk>/", InvoicePaidView.as_view(), name="invoice-paid"),
    path("delete/<str:pk>/", InvoiceDeleteView.as_view(), name="invoice-delete"),
    path("edit/<str:pk>/", InvoiceUpdateView.as_view(), name="invoice-edit"),
    path("update/<str:pk>/", UpdateInvoiceView.as_view(), name="invoice-update"),
    path("challan/<str:invoice_id>/", DeliveryChallanView.as_view(), name="generate_challan"),
    path('challan/delete/<str:challan_id>/', DeleteDeliveryChallanView.as_view(), name='delete_challan'),

]

src/services/project/urls.py
from django.urls import path

from .views import (
    ProjectView,
    ProjectCreateView,
    ProjectDetailView,
    AddBudgetView,
    StartProjectView,
    ProjectFinances,
    CreateProjectCash,
    ProjectUpdateView,
    ProjectExpensesView,
    ProjectInvoiceView,
    ModalCustomerCreateView,
    ProjectDeleteView,
)

app_name = "project"
urlpatterns = [
    path("", ProjectView.as_view(), name="index"),
    path("create/", ProjectCreateView.as_view(), name="create"),
    path("<str:pk>/detail/", ProjectDetailView.as_view(), name="detail"),
    path("<str:pk>/start-project/", StartProjectView.as_view(), name="start_project"),
    path("<str:pk>/update/", ProjectUpdateView.as_view(), name="update"),
    path("<str:pk>/transfer/", CreateProjectCash.as_view(), name="transfer_to_cash"),
    path("<str:pk>/add-budget/", AddBudgetView.as_view(), name="add_budget"),
    path("<str:pk>/expenses/", ProjectExpensesView.as_view(), name="expenses"),
    path("<str:pk>/invoices/", ProjectInvoiceView.as_view(), name="invoices"),
    path("<str:pk>/finances/", ProjectFinances.as_view(), name="finances"),
    path("<str:pk>/delete/", ProjectDeleteView.as_view(), name="delete"),
]

urlpatterns += [
    path(
        "customer/modal-create/",
        ModalCustomerCreateView.as_view(),
        name="customer_modal_create",
    ),
]

src/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('src.web.dashboard.urls')),
    path('invoice/', include('src.services.invoice.urls')),
    path('customer/', include('src.services.customer.urls')),
    path('projects/', include('src.services.project.urls')),
    path('quotation/', include('src.services.quotation.urls')),
    path('loans/', include('src.services.loan.urls')),
    path('expense/', include('src.services.expense.urls')),
    path('assets/', include('src.services.assets.urls')),
    path('vendor/', include('src.services.vendor.urls')),
    path('transaction/', include('src.services.transaction.urls')),
    path('charts/', include('src.services.charts.urls')),
    path('accounts/', include('src.web.accounts.urls')),
]

src/services/project/models.py
from django.db import models
from django.db.models import Sum

from src.core.models import BillingAddress

# from src.services.transaction.models import Ledger


class Project(models.Model):
    class ProjectStatus(models.TextChoices):
        DRAFT = "DF", "Draft"
        AWAITING = "AW", "Awaiting Quote Approval"
        CANCELLED = "CL", "Cancelled"
        IN_PROGRESS = "IP", "In Progress"
        FINISHED = "FN", "Finished"

    class BudgetSource(models.TextChoices):
        CASH = "CASH", "Cash in Hand"
        ACCOUNT = "ACC", "Account"

    project_name = models.CharField(
        max_length=255, help_text="Name of the project", blank=True
    )
    description = models.TextField(
        help_text="Description of the project", blank=True, null=True
    )
    customer = models.ForeignKey(
        "customer.Customer", on_delete=models.CASCADE, related_name="projects"
    )

    # Project Assets
    project_cash = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0.00,
        help_text="Cash in hand assigned to the project",
    )
    project_account_balance = models.DecimalField(
        max_digits=12,
        decimal_places=2,
        default=0.00,
        help_text="Account funds assigned to the project",
    )

    project_status = models.CharField(
        max_length=2,
        choices=ProjectStatus.choices,
        default=ProjectStatus.DRAFT,
        help_text="Current status of the project",
    )

    budget_source = models.CharField(
        max_length=6,
        choices=BudgetSource.choices,
        default=BudgetSource.CASH,
        help_text="Source of the project budget",
    )

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.project_name or 'Project'}"

    def get_total_budget(self):
        return self.project_cash + self.project_account_balance

    def get_address(self):
        billing_address = BillingAddress.objects.filter(
            customer_id=self.customer.pk
        ).first()
        if billing_address:
            return f"{billing_address.city} - {billing_address.state}"
        else:
            return f"Customer Address Not Defined"

    def get_trial_balance(self):
        total_invoices = (
            self.invoices.aggregate(total=Sum("total_amount"))["total"] or 0
        )
        total_expenses = self.expenses.aggregate(total=Sum("amount"))["total"] or 0
        cash_balance = self.project_cash
        account_balance = self.project_account_balance

        return {
            "Total Invoices (Credit)": total_invoices,
            "Total Expenses (Debit)": total_expenses,
            "Cash Balance": cash_balance,
            "Account Balance": account_balance,
            "Net Balance": (
                cash_balance + account_balance + total_invoices - total_expenses
            ),
        }

    def generate_trial_balance(self):
        trial_balance = []
        invoices_total = (
            self.invoices.aggregate(total=Sum("total_amount"))["total"] or 0
        )
        expenses_total = self.expenses.aggregate(total=Sum("amount"))["total"] or 0

        trial_balance.append({"Account": "Invoices (Credit)", "Amount": invoices_total})
        trial_balance.append({"Account": "Expenses (Debit)", "Amount": expenses_total})
        trial_balance.append(
            {"Account": "Net Balance", "Amount": invoices_total - expenses_total}
        )
        return trial_balance

    def delete(self):
        # Ledger.objects.all().filter(project_id=self.pk).delete(
        #     without_repercussions=True
        # )
        super().delete()

src/services/project/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Row, Column, Submit
from django import forms
from crispy_forms.layout import HTML

from .models import Project
from ..assets.models import AccountBalance


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["project_name", "description", "customer"]

        labels = {
            "project_name": "Project Name:",
            "description": "Project Description:",
            "customer": "Customer:",
        }

        widgets = {
            "project_name": forms.TextInput(
                attrs={"class": "form-control", "placeholder": "Enter project name"}
            ),
            "description": forms.Textarea(
                attrs={"class": "form-control", "placeholder": "Describe the project"}
            ),
            "customer": forms.Select(attrs={"class": "form-control"}),
        }

    def clean(self):
        cleaned_data = super().clean()
        fields_to_validate = [
            "project_name",
        ]

        for field in fields_to_validate:
            value = cleaned_data.get(field)
            if value and not all(char.isalnum() or char.isspace() for char in value):
                self.add_error(
                    field,
                    f"{field.replace('_', '  ').capitalize()} should only contain alphanumeric characters and spaces.",
                )

        return cleaned_data

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"
        self.helper.form_class = "row g-3"
        self.helper.layout = Layout(
            Row(
                Column("project_name", css_class="form-group col-md-12 mb-3"),
            ),
            Row(
                Column("description", css_class="form-group col-md-12 mb-3"),
            ),
            Row(
                Column("customer", css_class="form-group col-md-9 mb-3"),
                Column(
                    HTML(
                        '<button type="button" class="btn btn-outline-primary btn-sm mt-3" data-bs-toggle="modal" data-bs-target="#addCustomerModal">Add Customer</button>'
                    ),
                    css_class="form-group col-md-3 mb-3",
                ),
                css_class="row",
            ),
            FormActions(
                Submit("submit", "Create Project", css_class="btn btn-primary")
            ),
        )


class AddBudgetForm(forms.Form):
    amount = forms.DecimalField(max_digits=12, decimal_places=2, label="Amount")
    source = forms.ModelChoiceField(
        queryset=AccountBalance.objects.all(),
        required=True,
        label="Bank Account (Source)",
    )
    reason = forms.CharField(
        label="Reason for Transaction", required=True, max_length=255
    )

    amount.widget.attrs.update({"class": "form-control", "placeholder": "Enter amount"})
    source.widget.attrs.update({"class": "form-control"})
    reason.widget.attrs.update({"class": "form-control"})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        first_account = AccountBalance.objects.first()
        if first_account:
            self.fields["source"].initial = first_account


class CreateProjectCashForm(forms.Form):
    amount = forms.DecimalField(max_digits=12, decimal_places=2, label="Amount")
    reason = forms.CharField(
        label="Reason for Transaction", required=True, max_length=255
    )

    reason.widget.attrs.update({"class": "form-control"})
    amount.widget.attrs.update({"class": "form-control", "placeholder": "Enter amount"})

src/services/project/templates/project/create_project_cash.html
{% extends 'dashboard/base.html' %}
{% block title %}Customer Detail{% endblock %}
{% load static %}
{% load project_tags %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="page-wrapper">
        <div class="page-content">
            <div class="container-fluid">


                <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                    <h4 class="page-title">
                        <a href="javascript:void(0);" onclick="history.back();">
                            <div class="btn btn-secondary btn-sm me-2">
                                <i class="fa fa-arrow-left me-1"></i>Go Back
                            </div>
                        </a>
                        Project Finance Detail</h4>
                    <div class="page-title-right">
                        <ol class="breadcrumb m-0">
                            <li class="breadcrumb-item"><a href="{% url 'project:index' %}">Project</a></li>
                            <li class="breadcrumb-item active">Finance</li>
                        </ol>
                    </div>

                </div>

                <div class="row justify-content-center">
                    <div class="col-md-6">
                    <div class="card bg-globe-img">
                        <h4 class="m-2 text-center">Transfer Project funds to Cash In Hand</h4>
                        <div class="card-body">
                            <form method="POST">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-primary mt-2 w-100">Transfer</button>
                            </form>
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div>
                </div>



            </div>
        </div>
    </div>

{% endblock %}

src/services/project/templates/project/customer_form_modal.html
{% load crispy_forms_tags %}
<form method="post" id="addCustomerForm">
    {% csrf_token %}
    {% crispy form %}
</form>

src/services/project/templates/project/finances.html
{% extends 'dashboard/base.html' %}
{% block title %}Customer Detail{% endblock %}
{% load static %}
{% load project_tags %}
{% load crispy_forms_tags %}


{% block content %}

    <div class="page-wrapper">
        <div class="page-content">
            <div class="container-fluid">


                <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                    <h4 class="page-title">
                        <a class="btn btn-secondary btn-sm" href="{% url 'project:detail' project.pk %}"><i
                                class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                        Project Finance Detail</h4>

                </div>


                <div class="col-md-12">
                    <div class="card bg-globe-img">
                        <div class="card-body">
                            <div>
                                <div class="d-flex justify-content-between align-items-center">
                                    <span class="fs-16 fw-semibold">Project Balance</span>
                                    <a href="{% url 'project:transfer_to_cash' project.pk %}"><span
                                            class="btn btn-primary">Transfer to Project Cash</span></a>
                                </div>

                                <h4 class="my-2 fs-24 fw-semibold">{{ project.get_total_budget }} <small
                                        class="font-14">PKR</small></h4>

                                <span class="fs-16 fw-semibold">Money Spent from wallet:<span
                                        class="badge bg-danger-subtle text-danger fs-11 fw-medium px-2 ms-1 mb-1">{{ budget_assigned }} PKR</span></span>
                                <br>
                                <span class="fs-16 fw-semibold">Money From Client <small>(Paid Invoices)</small> <span
                                        class="badge bg-success-subtle text-success fs-11 fw-medium px-2 ms-1 mb-1">{{ money_form_invoice }} PKR </span></span>
                                <br>
                                <span class="fs-16 fw-semibold">Receivables <small>(UnpaidInvoices)</small> <span
                                        class="badge bg-danger-subtle text-danger fs-11 fw-medium px-2 ms-1 mb-1">{{ invoice_receivables }} PKR </span></span>
                                <br>
                                <span class="fs-16 fw-semibold">Project Expenditure: <small>(Expenses Created)</small> <span
                                        class="badge bg-warning-subtle text-warning fs-11 fw-medium px-2 ms-1 mb-1">{{ project_expenditure }} PKR </span></span>
                                <br>
                                <span class="fs-16 fw-semibold">Loan Payable: <small>(Loans Lended)</small> <span
                                        class="badge bg-danger-subtle text-danger fs-11 fw-medium px-2 ms-1 mb-1">{{ loans }} PKR </span></span>
{#                                <a href="{% url 'charts:project-expense-journal' project.pk %}"><span#}
{#                                        class="btn btn-warning float-end">Download</span></a>#}

                            </div>
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div>


                {# STATISTICS #}
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card shadow-lg">
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-6">
                                        <h4 class="card-title">Expense Summary</h4>
                                    </div>
                                    <div class="col-md-6 text-end">
                                        <form method="get" action="">
                                            <div class="col-md-4 mb-2 float-end">
                                                <select name="transaction_type" id="transaction_type"
                                                        class="form-select" onchange="this.form.submit()">
                                                    <option value="">All Transaction Types</option>
                                                    {% for code, name in transaction_types %}
                                                        <option value="{{ code }}"
                                                                {% if selected_transaction_type == code %}selected{% endif %}>
                                                            {{ name }}
                                                        </option>
                                                    {% endfor %}
                                                </select>
                                            </div>
                                        </form>

                                    </div>


                                </div>
                                <table class="table mb-0">
                                    <thead class="table-light">
                                    <tr>
                                        <th class="border-top-0">Transaction Type</th>
                                        <th class="border-top-0">Project</th>
                                        <th class="border-top-0">Source</th>
                                        <th class="border-top-0 text-center">Destination</th>
                                        <th class="border-top-0 ">Reason</th>
                                        <th class="border-top-0">Amount</th>

                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for object in ledger_entries %}
                                        <tr>
                                            <td><a href="#"><span
                                                    class="badge bg-danger-subtle text-danger fs-11 fw-medium px-2">{{ object.transaction_type }}</span></a>
                                            </td>
                                            <td>{{ object.project }}</td>
                                            <td>
                                                {{ object.source }}
                                            </td>
                                            <td class="text-center">{{ object.destination }}</td>
                                            <td class="">{{ object.reason|slice:'100' }}</td>
                                            <td>{{ object.amount }} PKR</td>

                                        </tr>
                                    {% endfor %}


                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>

{% endblock %}

src/services/project/templates/project/project_index.html
{% extends 'dashboard/base.html' %}
{% block title %}Projects{% endblock %}
{% load static %}
{% load project_tags %}


{% block content %}
    <div class="page-wrapper">

        <!-- Page Content-->
        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                            <h4 class="page-title">Projects</h4>

                        </div><!--end page-title-box-->
                    </div><!--end col-->
                </div><!--end row-->

                <div class="row justify-content-center">
                    <div class="col-md-12 col-lg-12">
                        <div class="card">
                            <div class="card-body pt-0">
                                <div class="mb-2 row mt-3">
                                    <div class="col-sm-6">
                                        <form method="get" action="" class="d-flex align-items-center">
                                            <input
                                                    class="form-control search-box me-2 mb-2 d-inline-block"
                                                    placeholder="Search..."
                                                    name="q"
                                                    value="{{ search_query|default:'' }}"/>
                                            <button class="btn btn-primary mb-2" type="submit">Search</button>
                                        </form>
                                    </div>
                                    <div class="col-sm-6 float-end">
                                        <div class="text-sm-end">
                                            <a href="{% url 'project:create' %}"
                                               class="btn btn-primary btn-rounded waves-effect waves-light addContact-modal mb-2 btn btn-primary">
                                                <i class="mdi mdi-plus me-1"></i> New Project
                                            </a>
                                        </div>
                                    </div>
                                </div>

                                <div class="table-responsive">
                                    <table class="table mb-0">
                                        <thead class="table-light">
                                        <tr>
                                            <th class="border-top-0">Name</th>
                                            <th class="border-top-0">Client</th>
                                            <th class="border-top-0">Description</th>
                                            <th class="border-top-0">Budget</th>
                                            <th class="border-top-0">Status</th>
                                            <th class="border-top-0">Delete</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for project in projects %}
                                            <tr>
                                                <td>
                                                    <a href="{% url 'project:detail' project.id %}">{{ project.project_name }}</a>
                                                </td>
                                                <td>{{ project.customer.get_full_name }}</td>
                                                <td>{{ project.description|slice:20 }}</td>
                                                <td>{{ project.get_total_budget }}</td>
                                                <td>
                <span class="badge bg-{{ project.project_status|status_badge_color }} text-{{ project.project_status|status_text_color }} fs-11 fw-medium px-2 text-white">
                    {{ project.get_project_status_display }}
                </span>
                                                </td>
                                                <td>
                                                    <a href="{% url 'project:delete' project.id %}"
                                                       class="btn btn-danger btn-sm">
                                                        <i class="fa fa-trash-alt"></i>
                                                    </a>

                                            </tr>
                                        {% empty %}
                                            <tr>
                                                <td colspan="6">No projects found.</td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table>
                                    <!--end table-->
                                </div><!--end /div-->
                                <div class="d-lg-flex justify-content-lg-between mt-2">

                                    <div>
                                        <ul class="pagination mt-1">
                                            <!-- Previous Button -->
                                            {% if projects.has_previous %}
                                                <li class="page-item">
                                                    <a class="page-link"
                                                       href="?q={{ search_query }}&page={{ projects.previous_page_number }}"
                                                       tabindex="-1">Previous</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item disabled">
                                                    <a class="page-link" href="#" tabindex="-1">Previous</a>
                                                </li>
                                            {% endif %}

                                            <!-- Page Numbers -->
                                            {% for num in projects.paginator.page_range %}
                                                {% if projects.number == num %}
                                                    <li class="page-item active">
                                                        <a class="page-link" href="#">{{ num }}</a>
                                                    </li>
                                                {% else %}
                                                    <li class="page-item">
                                                        <a class="page-link"
                                                           href="?q={{ search_query }}&page={{ num }}">{{ num }}</a>
                                                    </li>
                                                {% endif %}
                                            {% endfor %}

                                            <!-- Next Button -->
                                            {% if projects.has_next %}
                                                <li class="page-item">
                                                    <a class="page-link"
                                                       href="?q={{ search_query }}&page={{ projects.next_page_number }}">Next</a>
                                                </li>
                                            {% else %}
                                                <li class="page-item disabled">
                                                    <a class="page-link" href="#">Next</a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </div>

                                </div>
                            </div><!--end card-body-->
                        </div><!--end card-->
                    </div> <!--end col-->

                </div><!--end row-->

            </div><!-- container -->

            <!--end footer-->
        </div>
        <!-- end page content -->
    </div>
{% endblock %}