root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler403, handler500

from django.views.static import serve

from root.settings import MEDIA_ROOT, STATIC_ROOT
from src.core.views import handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.urls')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" HANDLERS FOR 404 AND 500 ERRORS -------------------------------------------------------------------------------- """
handler404 = handler404
handler403 = handler403
handler500 = handler500

src/services/assets/urls.py
from django.urls import path

from .views import (
    IndexView,
    AccountBalanceUpdateView,
    AccountBalanceList,
    AccountBalanceCreateView,
    CashInHandDetailView,
    AddCashInHandView,
    AccountBalanceDetailView,
    AddAccountBalanceView,
    AccountBalanceDeleteView, AccountBalanceTransferView
)

app_name = "assets"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("accounts/", AccountBalanceList.as_view(), name="accounts"),
    path(
        "accounts/create/", AccountBalanceCreateView.as_view(), name="accounts_create"
    ),
    path(
        "account/<str:pk>/update/",
        AccountBalanceUpdateView.as_view(),
        name="account_balance_update",
    ),
    path(
        "account/<str:pk>/detail/",
        AccountBalanceDetailView.as_view(),
        name="account-detail",
    ),
    path(
        "account/<str:pk>/add-balance/",
        AddAccountBalanceView.as_view(),
        name="add-balance",
    ),
    path("cash-in-hand/add/", AddCashInHandView.as_view(), name="add-cash-in-hand"),
    path("cash-in-hand/", CashInHandDetailView.as_view(), name="cash_list"),

    path('delete/<str:pk>/', AccountBalanceDeleteView.as_view(), name='account_balance_delete'),
    path('transfer/<str:pk>/', AccountBalanceTransferView.as_view(), name='transfer'),
]

src/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('src.web.dashboard.urls')),
    path('invoice/', include('src.services.invoice.urls')),
    path('customer/', include('src.services.customer.urls')),
    path('projects/', include('src.services.project.urls')),
    path('quotation/', include('src.services.quotation.urls')),
    path('loans/', include('src.services.loan.urls')),
    path('expense/', include('src.services.expense.urls')),
    path('assets/', include('src.services.assets.urls')),
    path('vendor/', include('src.services.vendor.urls')),
    path('transaction/', include('src.services.transaction.urls')),
    path('charts/', include('src.services.charts.urls')),
    path('accounts/', include('src.web.accounts.urls')),
]

src/services/assets/models.py
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models import Sum

from src.services.expense.models import ExpenseCategory


# Create your models here.


class CashInHand(models.Model):
    name = models.CharField(max_length=255, unique=True)
    balance = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateField(auto_now_add=True, null=True)

    def adjust_balance(self, amount, transaction_type):
        """
        Adjusts the account balance based on the transaction type. THIS CREDIT DOES NOT REFER TO AMOUNT BEING CREDITED
        INTO ACCOUNT BALANCE, RATHER AMOUNT BEING CREDITED TO A PROJECT BUDGET
        :param amount:
        :param transaction_type:
        :return:
        """
        if transaction_type == "CREDIT":
            if self.balance < amount:
                raise ValueError("Insufficient cash in hand")
            else:
                self.balance -= amount
        elif transaction_type == "DEBIT":
            self.balance += amount
        self.save()

    def save(self, *args, **kwargs):
        if not self.pk and CashInHand.objects.exists():
            return False
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Cash in Hand - Balance: {self.balance}"

    def get_name(self):
        return self.account_name


class AccountBalance(models.Model):
    account_name = models.CharField(max_length=255, unique=True)
    balance = models.DecimalField(max_digits=12, decimal_places=2, default=0.00)
    starting_balance = models.DecimalField(
        max_digits=12, decimal_places=2, default=0.00, null=True, blank=True
    )
    updated_at = models.DateTimeField(auto_now=True)
    created_at = models.DateField(auto_now_add=True, null=True)

    def adjust_balance(self, amount, transaction_type):
        """
        Adjusts the account balance based on the transaction type. THIS CREDIT DOES NOT REFER TO AMOUNT BEING CREDITED
        INTO ACCOUNT BALANCE, RATHER AMOUNT BEING CREDITED TO A PROJECT BUDGET
        :param amount:
        :param transaction_type:
        :return:
        """
        if transaction_type == "CREDIT":
            if self.balance < amount:
                raise ValueError("Insufficient funds in account")
            else:
                self.balance -= amount
        elif transaction_type == "DEBIT":
            self.balance += amount
        self.save()

    @classmethod
    def get_total_balance(cls):
        """
        Calculates the sum of all account balances.
        :return: Decimal - Total balance across all accounts
        """
        total_balance = cls.objects.aggregate(total=Sum("balance"))["total"]
        return total_balance or 0

    def __str__(self):
        return f"{self.account_name}"

    @classmethod
    def deduct_from_balance(cls, amount):
        accounts = cls.objects.filter(balance__gt=0).order_by("-balance")
        for account in accounts:
            if amount <= 0:
                break
            if account.balance >= amount:
                account.balance -= amount
                account.save()
                amount = 0
            else:
                amount -= account.balance
                account.balance = 0
                account.save()
        if amount > 0:
            raise ValidationError("Insufficient account balance.")

    def save(self, *args, **kwargs):
        if not self.pk:
            self.starting_balance = self.balance
            super().save(*args, **kwargs)
        super().save(*args, **kwargs)

    def get_name(self):
        return self.account_name

src/services/assets/forms.py
from django import forms
from .models import CashInHand, AccountBalance


class CashInHandForm(forms.Form):
    balance = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={"class": "form-control", "placeholder": "Enter balance"}
        ),
        required=True,
    )
    source = forms.ModelChoiceField(
        queryset=AccountBalance.objects.all(),
        label="Select Source",
        widget=forms.Select(attrs={"class": "form-control"}),
    )

    reason = forms.CharField(
        required=True,
        label="Reason",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Reason"}
        ),
    )


class AccountBalanceForm(forms.ModelForm):
    class Meta:
        model = AccountBalance
        fields = ["balance"]
        widgets = {
            "balance": forms.NumberInput(
                attrs={"class": "form-control", "placeholder": "Enter starting balance"}
            ),
        }


class AddBalance(forms.Form):
    balance = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={"class": "form-control", "placeholder": "Enter balance"}
        ),
        required=True,
    )
    source = forms.CharField(
        required=True,
        label="Source",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Source"}
        ),
    )


class TransferForm(forms.Form):
    destination = forms.ModelChoiceField(
        queryset=AccountBalance.objects.none(),  # Set an empty queryset initially
        label="Select Destination",
        widget=forms.Select(attrs={"class": "form-control"}),
    )
    amount = forms.DecimalField(
        max_digits=10,
        decimal_places=2,
        widget=forms.NumberInput(
            attrs={"class": "form-control", "placeholder": "Enter amount"}
        ),
        required=True,
    )
    reason = forms.CharField(
        required=True,
        label="Reason",
        max_length=100,
        widget=forms.TextInput(
            attrs={"class": "form-control", "placeholder": "Reason"})
    )

    def __init__(self, *args, current_account=None, **kwargs):
        super().__init__(*args, **kwargs)
        if current_account:
            self.fields["destination"].queryset = AccountBalance.objects.exclude(pk=current_account.pk)

src/services/assets/views.py
from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.db import transaction
from django.db.models import Sum, Q
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import TemplateView, UpdateView, ListView, DetailView
from django.views.generic.edit import CreateView, DeleteView, FormView

from .forms import CashInHandForm, TransferForm
from .models import CashInHand, AccountBalance
from ..project.bll import add_general_cash_in_hand, add_account_balance, transfer_balance
from ...core.mixins import AdminRequiredMixin
from ...web.dashboard.utils import ledger_filter
from .forms import AddBalance

class IndexView(AdminRequiredMixin, LoginRequiredMixin, TemplateView):
    template_name = "assets/assets_index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        cash_in_hand = CashInHand.objects.first()
        context["cash_in_hand"] = cash_in_hand.balance if cash_in_hand else 0

        account_balance = AccountBalance.objects.aggregate(
            total_balance=Sum("balance")
        )["total_balance"]
        accounts = AccountBalance.objects.count()
        context["account_balance"] = account_balance if account_balance else 0
        context["accounts"] = accounts if accounts else 0

        return context


class CashInHandDetailView(AdminRequiredMixin, LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        cashinhand = CashInHand.objects.first() or 0

        object_list = ledger_filter(source=cashinhand, destination=cashinhand)

        # Pagination setup
        page = request.GET.get("page", 1)
        paginator = Paginator(object_list, 20)

        try:
            paginated_object_list = paginator.page(page)
        except PageNotAnInteger:
            paginated_object_list = paginator.page(1)
        except EmptyPage:
            paginated_object_list = paginator.page(paginator.num_pages)

        context = {
            "cashinhand": cashinhand,
            "object_list": paginated_object_list,  # Use the paginated list here
        }
        return render(request, "assets/cashinhand.html", context)


# IDK IF IM SURE ABOUT ANY OF THIS.
class AddCashInHandView(AdminRequiredMixin, LoginRequiredMixin, FormView):
    form_class = CashInHandForm
    template_name = "assets/cashinhand_form.html"

    @transaction.atomic
    def form_valid(self, form):
        amount = form.cleaned_data["balance"]
        source_id = form.cleaned_data["source"]
        reason = form.cleaned_data["reason"]

        account = source_id
        if amount <= 0:
            form.add_error("balance", "The amount must be greater than zero.")
            return self.form_invalid(form)

        if amount > account.balance:
            form.add_error(
                "balance", "The amount you entered is greater than your balance."
            )
            return self.form_invalid(form)

        add_general_cash_in_hand(
            amount=amount,
            source=source_id,
            reason=reason,
        )
        # Show a success message and redirect to a success page
        messages.success(
            self.request,
            f"Cash in hand updated successfully. Added: {amount}",
        )
        messages.success(self.request, "Cash in hand updated successfully.")
        return super().form_valid(form)

    def form_invalid(self, form):
        # Re-render the template with the form containing errors
        return render(self.request, self.template_name, {"form": form})

    def get_success_url(self):
        # Redirect to a page of your choice after a successful form submission
        return reverse_lazy("assets:cash_list")


class CashInHandDeleteView(AdminRequiredMixin, LoginRequiredMixin, DeleteView):
    model = CashInHand
    template_name = "cashinhand_confirm_delete.html"
    success_url = reverse_lazy("cashinhand_list")


class AccountBalanceCreateView(AdminRequiredMixin, LoginRequiredMixin, CreateView):
    model = AccountBalance
    fields = ["account_name", "balance"]
    success_url = reverse_lazy("assets:accounts")


class AccountBalanceList(AdminRequiredMixin, LoginRequiredMixin, ListView):
    model = AccountBalance
    paginate_by = 20


class AccountBalanceUpdateView(AdminRequiredMixin, LoginRequiredMixin, UpdateView):
    model = AccountBalance
    fields = ["account_name", "balance"]
    success_url = reverse_lazy("assets:accounts")


class AccountBalanceDeleteView(AdminRequiredMixin, LoginRequiredMixin, DeleteView):
    model = AccountBalance
    template_name = "assets/accountbalance_confirm_delete.html"
    success_url = reverse_lazy("assets:accounts")


class AccountBalanceDetailView(AdminRequiredMixin, LoginRequiredMixin, DetailView):
    model = AccountBalance

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        object_list = ledger_filter(source=self.object, destination=self.object)

        paginator = Paginator(object_list, 20)
        page = self.request.GET.get("page")
        paginated_object_list = paginator.get_page(page)

        context["object_list"] = paginated_object_list

        return context

class AddAccountBalanceView(AdminRequiredMixin, LoginRequiredMixin, FormView):
    form_class = AddBalance
    template_name = "assets/add_balance.html"

    def get_object(self):
        pk = self.kwargs.get("pk")
        return AccountBalance.objects.get(pk=pk)

    @transaction.atomic
    def form_valid(self, form):
        amount = form.cleaned_data["balance"]
        source = form.cleaned_data["source"]
        account = self.get_object()

        if amount <= 0:
            form.add_error("balance", "The amount must be greater than zero.")
            return self.form_invalid(form)

        add_account_balance(
            amount=amount,
            account_pk=account.pk,
            reason=source,
        )
        # Show a success message and redirect to a success page
        messages.success(
            self.request,
            f"Account balance updated successfully. Added: {amount}",
        )
        return super().form_valid(form)

    def form_invalid(self, form):
        # Re-render the template with the form containing errors
        return render(self.request, self.template_name, {"form": form})

    def get_success_url(self):
        # Redirect to a page of your choice after a successful form submission
        return reverse_lazy("assets:accounts")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["account"] = self.get_object()
        return context



class AccountBalanceTransferView(LoginRequiredMixin, AdminRequiredMixin, FormView):
    template_name = "assets/transfer_balance.html"
    form_class = TransferForm

    def get_account(self):
        """Retrieve the account or return 404 if not found."""
        return get_object_or_404(AccountBalance, pk=self.kwargs.get("pk"))

    def get_form_kwargs(self):
        """Pass the current account to the form."""
        kwargs = super().get_form_kwargs()
        kwargs["current_account"] = self.get_account()
        return kwargs

    def form_valid(self, form):
        """Handle successful form submission."""
        account = self.get_account()
        destination = form.cleaned_data["destination"]
        amount = form.cleaned_data["amount"]
        reason = form.cleaned_data["reason"]

        if amount <= 0:
            form.add_error("amount", "The amount must be greater than zero.")
            return self.form_invalid(form)

        if amount > account.balance:
            form.add_error("amount", "The amount you entered is greater than your balance.")
            return self.form_invalid(form)

        # Perform the transfer
        transfer_balance(amount=amount, source=account, destination=destination, reason=reason)

        messages.success(self.request, f"Transferred {amount} to {destination.account_name} successfully.")
        return redirect(reverse("assets:account-detail", kwargs={"pk": account.pk}))

    def form_invalid(self, form):
        """Handle invalid form submissions."""
        return self.render_to_response(self.get_context_data(form=form, account=self.get_account()))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["account"] = self.get_account()
        return context

src/services/assets/templates/assets/accountbalance_confirm_delete.html
{% extends 'dashboard/base.html' %}
{% block title %} Delete {% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


    <div class="page-wrapper">
        <div class="page-content">
            <div class="container-fluid">


                <div class="row justify-content-center mt-3">
                    <div class="col-md-6">
                        <div class="alert alert-danger" role="alert">
                            <strong>Note:</strong> All the objects related to {{ object }} will become NULL.
                        </div>
                        <div class="card shadow-lg">
                            <div class="card-body">
                                <h5 class="ms-2">Are you sure you want to delete "{{ object }}"?</h5>
                                <p class="ms-2 text-danger">This action can not be undone</p>

                                <form method="post">{% csrf_token %}
                                    {{ form }}
                                    <a href="{% url 'assets:accounts' %}">
                                        <div class="btn btn-secondary me-2"><i class="fa fa-arrow-left me-1"></i>Go
                                            Back
                                        </div>
                                    </a>
                                    <input class="btn btn-danger float-end" type="submit" value="Confirm">


                                </form>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
{% endblock %}

src/services/assets/templates/assets/accountbalance_form.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Customer{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="page-wrapper">

        <!-- Page Content-->
        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="page-title-box d-md-flex justify-content-md-between align-items-center">

                            <h4 class="page-title">
                                <a class="btn btn-secondary btn-sm" href="{% url 'assets:accounts' %}"><i class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                                Account Balance</h4>

                        </div><!--end page-title-box-->
                    </div><!--end col-->
                </div><!--end row-->

                <div class="row justify-content-center">
                    {% if object %}
                        <h4 class="text-center">Update Balance</b> </h4>
                    {% else %}
                        <h4 class="text-center">Create Account</b> </h4>
                    {% endif %}

                    <div class="col-md-12 col-lg-6">
                        <div class="card border-2 shadow-lg">
                            <div class="card-body">
                                <form method="post" class="form">
                                    {% csrf_token %}
                                    {{ form|crispy }}
                                    <button type="submit" class="btn btn-primary mt-2">Update</button>
                                </form>
                            </div><!--end card-body-->
                        </div><!--end card-->
                    </div> <!--end col-->
                </div><!--end row-->

            </div><!-- container -->


            <!--end footer-->
        </div>
        <!-- end page content -->
    </div>
{% endblock %}

src/services/assets/templates/assets/accountbalance_list.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Customer{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


    <div class="page-wrapper">
        <div class="page-content">
            <div class="container-fluid">

                <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                    <h4 class="page-title">
                        <a class="btn btn-secondary btn-sm" href="{% url 'assets:index' %}"><i class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                        Accounts</h4>

                </div>

                <div class="card">
                    <div class="card-header">
                        <div class="row align-items-center">
                            <div class="col">
                                <h4 class="card-title">All Accounts</h4>
                            </div><!--end col-->
                            <div class="col-auto">
                                <a href="{% url 'assets:accounts_create' %}">
                                    <div class="btn btn-primary"> Add Account</div>
                                </a>
                            </div><!--end col-->
                        </div>  <!--end row-->
                    </div><!--end card-header-->
                    <div class="card-body pt-0">
                        <div class="table-responsive">
                            <table class="table mb-0">
                                <thead class="table-light">
                                <tr>
                                    <th class="border-top-0">Name</th>
                                    <th class="border-top-0">Balance</th>
                                    <th class="border-top-0">Updated at</th>
                                    <th class="border-top-0">Starting Balance</th>
                                    <th class="border-top-0">Delete</th>
                                </tr><!--end tr-->
                                </thead>
                                <tbody>
                                {% for object in object_list %}
                                    <tr>
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <img src="{% static 'img/user-default.jpeg' %}" height="40"
                                                     class="me-2 align-self-center rounded" alt="...">
                                                <div class="flex-grow-1 text-truncate align-self-center mt-1">
                                                    <h6 class="m-0"><a
                                                            href="{% url 'assets:account-detail' object.pk %}"> {{ object.account_name }}</a>
                                                    </h6>
                                                </div><!--end media body-->
                                            </div>
                                        </td>
                                        <td><a href="#" class="fs-12 text-primary">{{ object.balance }} PKR</a></td>
                                        <td>{{ object.updated_at }}</td>
                                        <td> {{ object.starting_balance }} PKR</td>
                                        <td> <a href="{% url 'assets:account_balance_delete' object.pk %}"><i class="text-danger fa fa-trash"></i></a> </td>
                                    </tr>
                                    <!--end tr-->
                                {% empty %}
                                    <p class="text-danger"> No Accounts Added</p>
                                {% endfor %}

                                </tbody>
                            </table> <!--end table-->
                        </div><!--end /div-->
                    </div><!--end card-body-->
                </div>

                <div>

                    <!-- Pagination controls -->
                    <ul class="pagination mt-1">
                        <!-- Previous Button -->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}" tabindex="-1">Previous</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#" tabindex="-1">Previous</a>
                            </li>
                        {% endif %}

                        <!-- Page Numbers -->
                        {% for num in paginator.page_range %}
                            {% if page_obj.number == num %}
                                <li class="page-item active">
                                    <a class="page-link" href="#">{{ num }}</a>
                                </li>
                            {% else %}
                                <li class="page-item">
                                    <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                                </li>
                            {% endif %}
                        {% endfor %}

                        <!-- Next Button -->
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a>
                            </li>
                        {% else %}
                            <li class="page-item disabled">
                                <a class="page-link" href="#">Next</a>
                            </li>
                        {% endif %}
                    </ul>
                </div>


            </div>
        </div>
    </div>


{% endblock %}

src/services/assets/templates/assets/add_balance.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Customer{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="page-wrapper">

        <!-- Page Content-->
        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                            <h4 class="page-title">
                                <a class="btn btn-secondary btn-sm" href="{% url 'assets:account-detail' account.pk %}"><i
                                        class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                                Add cash</h4>

                        </div><!--end page-title-box-->
                    </div><!--end col-->
                </div><!--end row-->

                <div class="row justify-content-center">
                    <h4 class="text-center">Add Balance</b> </h4>
                    <div class="col-md-12 col-lg-6">
                        <div class="card border-2 border-warning">
                            <div class="card-body">
                                <form method="post" class="form">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </div><!--end card-body-->
                        </div><!--end card-->
                    </div> <!--end col-->
                </div><!--end row-->

            </div><!-- container -->


            <!--end footer-->
        </div>
        <!-- end page content -->
    </div>
{% endblock %}

src/services/assets/templates/assets/cash_in_hand_update.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Customer{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<div class="page-wrapper">

    <!-- Page Content-->
    <div class="page-content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-12">
                    <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                        <h4 class="page-title">Update Cash in Hand</h4>
                        <div class="">
                            <ol class="breadcrumb mb-0">
                                <li class="breadcrumb-item"><a href="#">Approx</a>
                                </li><!--end nav-item-->
                                <li class="breadcrumb-item active">Cash in Hand</li>
                            </ol>
                        </div>
                    </div><!--end page-title-box-->
                </div><!--end col-->
            </div><!--end row-->

            <div class="row justify-content-center">
                <h4 class="text-center">Update Cash in hand</b> </h4>
                <div class="col-md-12 col-lg-6">
                    <div class="card border-2 border-warning">
                        <div class="card-body">
                            <form method="post" class="form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Update</button>
            </form>
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div> <!--end col-->
            </div><!--end row-->

        </div><!-- container -->



        <!--end footer-->
    </div>
    <!-- end page content -->
</div>
{% endblock %}