root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler403, handler500

from django.views.static import serve

from root.settings import MEDIA_ROOT, STATIC_ROOT
from src.core.views import handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.urls')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" HANDLERS FOR 404 AND 500 ERRORS -------------------------------------------------------------------------------- """
handler404 = handler404
handler403 = handler403
handler500 = handler500

src/services/assets/urls.py
from django.urls import path

from .views import (
    IndexView,
    AccountBalanceUpdateView,
    AccountBalanceList,
    AccountBalanceCreateView,
    CashInHandDetailView,
    AddCashInHandView,
    AccountBalanceDetailView,
    AddAccountBalanceView,
    AccountBalanceDeleteView, AccountBalanceTransferView
)

app_name = "assets"
urlpatterns = [
    path("", IndexView.as_view(), name="index"),
    path("accounts/", AccountBalanceList.as_view(), name="accounts"),
    path(
        "accounts/create/", AccountBalanceCreateView.as_view(), name="accounts_create"
    ),
    path(
        "account/<str:pk>/update/",
        AccountBalanceUpdateView.as_view(),
        name="account_balance_update",
    ),
    path(
        "account/<str:pk>/detail/",
        AccountBalanceDetailView.as_view(),
        name="account-detail",
    ),
    path(
        "account/<str:pk>/add-balance/",
        AddAccountBalanceView.as_view(),
        name="add-balance",
    ),
    path("cash-in-hand/add/", AddCashInHandView.as_view(), name="add-cash-in-hand"),
    path("cash-in-hand/", CashInHandDetailView.as_view(), name="cash_list"),

    path('delete/<str:pk>/', AccountBalanceDeleteView.as_view(), name='account_balance_delete'),
    path('transfer/<str:pk>/', AccountBalanceTransferView.as_view(), name='transfer'),
]

src/services/charts/urls.py
from django.urls import path
from .views import (
    ChartsIndex,
    generate_project_report,
    generate_bank_statements_view,
    project_expenses,
    yearly_report
)

app_name = "charts"

urlpatterns = [
    path("", ChartsIndex.as_view(), name="list"),
    path("project-report/<str:pk>/", generate_project_report, name="project-report"),
    path(
        "project-expense-sheet/<str:pk>/",
        project_expenses,
        name="project-expense-journal",
    ),
    path(
        "generate-bank-statements/",
        generate_bank_statements_view,
        name="generate_bank_statements",
    ),
    path('yearly-report/', yearly_report, name='yearly_report'),
]

src/services/loan/urls.py
from django.urls import path

from .forms import MiscLoanReturnForm
from .views import (
    LendLoanView, ReturnLoanView, LoanListView, LenderListView, LenderDetailView, LenderCreateView, MiscLoanCreateView,
    MiscLoanReturnView, LenderDeleteView
)

app_name = 'loan'
urlpatterns = [
    path('list/<int:pk>/', LoanListView.as_view(), name='list'),
    path('lend-loan/<int:pk>/', LendLoanView.as_view(), name='lend_loan'),
    path('return-loan/<int:pk>/', ReturnLoanView.as_view(), name='return_loan'),


    path('lender/', LenderListView.as_view(), name='lenders'),
    path('lender/create/', LenderCreateView.as_view(), name='lender-create'),
    path('lender/<str:pk>/', LenderDetailView.as_view(), name='lender-detail'),

    path('lend-misc-loan/<str:pk>/', MiscLoanCreateView.as_view(), name='lend-misc-loan'),
    path('return-misc-loan/<str:pk>/', MiscLoanReturnView.as_view(), name='return-misc-loan'),

    path('lender-delete/<str:pk>/', LenderDeleteView.as_view(), name='lender-delete'),

]

src/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('src.web.dashboard.urls')),
    path('invoice/', include('src.services.invoice.urls')),
    path('customer/', include('src.services.customer.urls')),
    path('projects/', include('src.services.project.urls')),
    path('quotation/', include('src.services.quotation.urls')),
    path('loans/', include('src.services.loan.urls')),
    path('expense/', include('src.services.expense.urls')),
    path('assets/', include('src.services.assets.urls')),
    path('vendor/', include('src.services.vendor.urls')),
    path('transaction/', include('src.services.transaction.urls')),
    path('charts/', include('src.services.charts.urls')),
    path('accounts/', include('src.web.accounts.urls')),
]

src/web/accounts/urls.py
from django.urls import path
from .views import (
    CustomLoginView,
    UserListView,
    CustomLogoutView,
    UserCreateView,
    UserUpdateView,
    UserDeleteView,
)

app_name = "accounts"

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("users/", UserListView.as_view(), name="list"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
]

urlpatterns += [
    path("create/", UserCreateView.as_view(), name="create"),
    path("<str:pk>/update/", UserUpdateView.as_view(), name="update"),
    path("<str:pk>/delete/", UserDeleteView.as_view(), name="delete"),
]

src/web/dashboard/urls.py
from django.urls import path, include
from . views import (
    HomeView,
)
app_name = 'dashboard'

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
]

src/web/dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import TemplateView
from django.db.models import Sum, Q

from src.services.assets.models import CashInHand, AccountBalance
from src.services.customer.models import Customer
from src.services.expense.models import Expense
from src.services.invoice.models import Invoice
from src.services.loan.models import Loan, MiscLoan
from src.services.transaction.models import Ledger
from src.services.vendor.models import Vendor
from src.web.dashboard.utils import get_monthly_income_expense


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard/dashboard.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        income, expense = get_monthly_income_expense()

        cash_in_hand = CashInHand.objects.first()
        cash_in_hand_balance = cash_in_hand.balance if cash_in_hand else 0
        account_balance_balance = (
            AccountBalance.objects.aggregate(total=Sum("balance"))["total"] or 0
        )

        context["cash_in_hand"] = cash_in_hand_balance
        context["income"] = income
        context["expense"] = expense
        context["account_balance"] = account_balance_balance
        context["total_balance"] = cash_in_hand_balance + account_balance_balance
        context["customer_count"] = Customer.objects.count()
        context["payable"] = (
            Loan.calculate_total_unpaid_amount()
            + MiscLoan.calculate_total_unpaid_amount()
        )
        context["receivables"] = Invoice.calculate_total_receivables()
        context["top_vendors"] = Vendor.objects.annotate(
            total_paid_expense=Sum(
                "expenses__amount",
                filter=Q(expenses__payment_status=Expense.PaymentStatus.PAID),
            )
        ).order_by("-total_paid_expense")[:8]
        context["transactions"] = Ledger.objects.order_by("-created_at")[:8]
        return context

templates/dashboard/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr" data-startbar="dark" data-bs-theme="light">
{% load static %}


<head>


    <meta charset="utf-8"/>
    <title>CATALYST | {% block title %}{% endblock %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta content="CRM FOR CATALYST COMS" name="CATALYST COMMUNICATIONS"/>
    <meta content="" name="author"/>
    {% block head %}

    {% endblock %}
    <meta name="csrf-token" content="{{ csrf_token }}">
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>


    <!-- App favicon -->
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}">


    <!-- App css -->
    <link href="{% static 'website/css/bootstrap.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'website/css/icons.min.css' %}" rel="stylesheet" type="text/css"/>
    <link href="{% static 'website/css/app.min.css' %}" rel="stylesheet" type="text/css"/>
    <script>
        // Check the saved theme in localStorage and apply it immediately
        (function () {
            var savedTheme = localStorage.getItem("theme");
            if (savedTheme) {
                document.documentElement.setAttribute("data-bs-theme", savedTheme);
            } else {
                document.documentElement.setAttribute("data-bs-theme", "light");
            }
        })();
    </script>

</head>
<style>
    body {
        zoom: 0.9;
    }
</style>

<body>

{% if messages %}
<div id="popupAlerts" class="position-fixed top-0 end-0 p-3" style="z-index: 1050;">
    {% for message in messages %}
    <div class="alert {% if message.tags == 'success' %}alert-success{% elif message.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show shadow-sm border-theme-white-2 rounded-pill mb-3"
         role="alert">
        <div class="d-inline-flex justify-content-center align-items-center thumb-xs {% if message.tags == 'success' %}bg-success{% elif message.tags == 'error' %}bg-danger{% endif %} rounded-circle mx-auto me-1">
            <i class="fas {% if message.tags == 'success' %}fa-check{% elif message.tags == 'error' %}fa-exclamation-triangle{% endif %} align-self-center mb-0 text-white"></i>
        </div>
        <strong>{% if message.tags == 'success' %}Well done!{% elif message.tags == 'error' %}Oh
            no!{% endif %}</strong> {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
</div>
{% endif %}


<!-- Top Bar Start -->
<div class="topbar d-print-none">
    <div class="container-fluid">
        <nav class="topbar-custom d-flex justify-content-between" id="topbar-custom">


            <ul class="topbar-item list-unstyled d-inline-flex align-items-center mb-0">
                <li>
                    <button class="nav-link mobile-menu-btn nav-icon" id="togglemenu">
                        <i class="iconoir-menu"></i>
                    </button>
                </li>

            </ul>
            <ul class="topbar-item list-unstyled d-inline-flex align-items-center mb-0">


                <li class="topbar-item">
                    <a class="nav-link nav-icon" href="javascript:void(0);" id="light-dark-mode">
                        <i class="iconoir-half-moon dark-mode"></i>
                        <i class="iconoir-sun-light light-mode"></i>
                    </a>
                </li>


                <li class="dropdown topbar-item">
                    <a class="nav-link dropdown-toggle arrow-none nav-icon" data-bs-toggle="dropdown" href="#"
                       role="button"
                       aria-haspopup="false" aria-expanded="false" data-bs-offset="0,19">
                        {% if request.user.image %}
                        <img src="{{ request.user.image.url }}" alt="" class="thumb-md rounded-circle">
                        {% else %}
                        <img src="https://placehold.co/400" alt="" class="thumb-md rounded-circle">
                        {% endif %}
                    </a>
                    <div class="dropdown-menu dropdown-menu-end py-0 "
                         style="position: absolute; inset: 0px 0px auto auto; margin: 0px; transform: translate3d(0px, 74.3802px, 0px);"
                         data-popper-placement="bottom-end">
                        <div class="d-flex align-items-center dropdown-item py-2 bg-secondary-subtle">
                            <div class="flex-shrink-0">
                                {% if request.user.image %}
                                <img src="{{ request.user.image.url }}" alt="" class="thumb-md rounded-circle">
                                {% else %}
                                <img src="https://placehold.co/400" alt=""
                                     class="thumb-md rounded-circle">
                                {% endif %}
                            </div>
                            <div class="flex-grow-1 ms-2 text-truncate align-self-center">
                                <h6 class="my-0 fw-medium text-dark fs-13">{{ request.user.first_name }}
                                    {{ request.user.last_name }}</h6>
                                <small class="text-muted mb-0">{{ request.user.role }}</small>
                            </div><!--end media-body-->
                        </div>
                        <div class="dropdown-divider mt-0"></div>


                        <a class="dropdown-item" href="#"><i
                                class="las la-question-circle fs-18 me-1 align-text-bottom"></i> Help Center</a>
                        <div class="dropdown-divider mb-0"></div>
                        <a class="dropdown-item text-danger" href="{% url 'accounts:logout' %}"><i
                                class="las la-power-off fs-18 me-1 align-text-bottom"></i> Logout</a>
                    </div>
                </li>
            </ul><!--end topbar-nav-->
        </nav>
        <!-- end navbar-->
        <!-- end navbar-->
    </div>
</div>
<!-- Top Bar End -->
<!-- leftbar-tab-menu -->
<div class="startbar d-print-none">
    <!--start brand-->
    <div class="brand">
        <a href="{% url 'dashboard:index' %}" class="logo">
                <span>
                    <img src="{% static 'website/images/logo-sm.png' %}" alt="logo-small" class="logo-sm">
                </span>
            <span class="">
                    <img src="{% static 'img/logo-lg.png' %}" alt="logo-large" class="logo-lg logo-light">
                    <img src="{% static 'imglogo-lg.png' %}" alt="logo-large" class="logo-lg logo-dark">
                </span>
        </a>
    </div>
    <!--end brand-->
    <!--start startbar-menu-->
    <div class="startbar-menu">
        <div class="startbar-collapse" id="startbarCollapse" data-simplebar>
            <div class="d-flex align-items-start flex-column w-100">
                <!-- Navigation -->
                <ul class="navbar-nav mb-auto w-100">
                    <li class="menu-label mt-2">
                        <span>Main</span>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'dashboard:index' %}">
                            <i class="iconoir-report-columns menu-icon"></i>
                            <span>Dashboard</span>
                            <span class="badge text-bg-info ms-auto">New</span>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'customer:index' %}">
                            <i class="iconoir-group menu-icon"></i>
                            <span>Customers</span>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'project:index' %}">
                            <i class="iconoir-task-list menu-icon"></i>
                            <span>Projects</span>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'expense:index' %}">
                            <i class="iconoir-credit-cards menu-icon"></i>
                            <span>Expenses</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'quotation:open-market' %}">
                            <i class="iconoir-paste-clipboard menu-icon"></i>
                            <span>Open Market</span>
                        </a>
                    </li>


                    <li class="menu-label mt-2">
                        <small class="label-border">
                            <div class="border_left hidden-xs"></div>
                            <div class="border_right"></div>
                        </small>
                        <span>MANAGEMENT</span>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'vendor:vendors' %}">
                            <i class="iconoir-community menu-icon"></i>
                            <span>Vendors</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'loan:lenders' %}">
                            <i class="iconoir-plug-type-l menu-icon"></i>
                            <span>Lenders</span>
                        </a>
                    </li>


                    {% if request.user.is_admin %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'transaction:list' %}">
                            <i class="iconoir-fingerprint-lock-circle menu-icon"></i>
                            <span>Transactions</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'charts:list' %}">
                            <i class="iconoir-cube-hole menu-icon"></i>
                            <span>Charts Of Accounts</span>
                        </a>
                    </li>


                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'assets:index' %}">
                            <i class="iconoir-candlestick-chart menu-icon"></i>
                            <span>Wallet</span>
                        </a>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:list' %}">
                            <i class="iconoir-group menu-icon"></i>
                            <span class="text-danger">User Management</span>
                        </a>
                    </li>
                    {% endif %}


                </ul><!--end navbar-nav--->
            </div>
        </div><!--end starter-collapse-->
    </div><!--end starter-menu-->
</div><!--end starter-->
<div class="startbar-overlay d-print-none"></div>
<!-- end leftbar-tab-menu-->

{% block content %}

{% endblock %}
<!-- end page-wrapper -->


<script>
    document.addEventListener('DOMContentLoaded', function () {
        {% if messages %}
            // Select the popup container
            var popupAlerts = document.getElementById('popupAlerts');

            // Show popup with a fade-in effect
            setTimeout(function () {
                popupAlerts.classList.add('show');
            }, 100); // Delay the appearance for a smooth effect

            // Automatically hide the alert after 5 seconds
            setTimeout(function () {
                var alerts = popupAlerts.querySelectorAll('.alert');
                alerts.forEach(function (alert) {
                    alert.classList.remove('show');
                });
            }, 5000); // Alert will fade out after 5 seconds
        {% endif %}
    });
</script>
<!-- vendor js -->

<script src="{% static 'website/libs/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'website/libs/simplebar/simplebar.min.js' %}"></script>


{#<script src="{% static '../../../apexcharts.com/samples/website/stock-prices.js' %}"></script>#}
<script src="{% static 'website/js/pages/index.init.js' %}"></script>
<script src="{% static 'website/js/DynamicSelect.js' %}"></script>
<script src="{% static 'website/js/app.js' %}"></script>

</body>
<!--end body-->


</html>