root/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls import handler404, handler403, handler500

from django.views.static import serve

from root.settings import MEDIA_ROOT, STATIC_ROOT
from src.core.views import handler404, handler403, handler500

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('src.urls')),
]

""" STATIC AND MEDIA FILES ----------------------------------------------------------------------------------------- """
urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': STATIC_ROOT}),
]

""" HANDLERS FOR 404 AND 500 ERRORS -------------------------------------------------------------------------------- """
handler404 = handler404
handler403 = handler403
handler500 = handler500

src/services/customer/urls.py
from django.urls import path

from .views import (
    CustomerView, CustomerCreateView, CustomerDetailView, BillingAddressAddView, BillingAddressUpdateView,
    CustomerUpdateView, CustomerDeleteView
)

app_name = 'customer'
urlpatterns = [
    path('', CustomerView.as_view(), name='index'),
    path('create/', CustomerCreateView.as_view(), name='create'),
    path('<str:pk>/', CustomerUpdateView.as_view(), name='update'),
    path('detail/<int:pk>/', CustomerDetailView.as_view(), name='detail'),
    path('delete/<int:pk>/', CustomerDeleteView.as_view(), name='delete'),


    path('billing-address-add/<int:pk>/', BillingAddressAddView.as_view(), name='billing-add'),
    path('billing-address-update/<int:pk>/', BillingAddressUpdateView.as_view(), name='billing-update'),

]

src/services/loan/urls.py
from django.urls import path

from .forms import MiscLoanReturnForm
from .views import (
    LendLoanView, ReturnLoanView, LoanListView, LenderListView, LenderDetailView, LenderCreateView, MiscLoanCreateView,
    MiscLoanReturnView, LenderDeleteView
)

app_name = 'loan'
urlpatterns = [
    path('list/<int:pk>/', LoanListView.as_view(), name='list'),
    path('lend-loan/<int:pk>/', LendLoanView.as_view(), name='lend_loan'),
    path('return-loan/<int:pk>/', ReturnLoanView.as_view(), name='return_loan'),


    path('lender/', LenderListView.as_view(), name='lenders'),
    path('lender/create/', LenderCreateView.as_view(), name='lender-create'),
    path('lender/<str:pk>/', LenderDetailView.as_view(), name='lender-detail'),

    path('lend-misc-loan/<str:pk>/', MiscLoanCreateView.as_view(), name='lend-misc-loan'),
    path('return-misc-loan/<str:pk>/', MiscLoanReturnView.as_view(), name='return-misc-loan'),

    path('lender-delete/<str:pk>/', LenderDeleteView.as_view(), name='lender-delete'),

]

src/services/project/urls.py
from django.urls import path

from .views import (
    ProjectView,
    ProjectCreateView,
    ProjectDetailView,
    AddBudgetView,
    StartProjectView,
    ProjectFinances,
    CreateProjectCash,
    ProjectUpdateView,
    ProjectExpensesView,
    ProjectInvoiceView,
    ModalCustomerCreateView,
    ProjectDeleteView,
)

app_name = "project"
urlpatterns = [
    path("", ProjectView.as_view(), name="index"),
    path("create/", ProjectCreateView.as_view(), name="create"),
    path("<str:pk>/detail/", ProjectDetailView.as_view(), name="detail"),
    path("<str:pk>/start-project/", StartProjectView.as_view(), name="start_project"),
    path("<str:pk>/update/", ProjectUpdateView.as_view(), name="update"),
    path("<str:pk>/transfer/", CreateProjectCash.as_view(), name="transfer_to_cash"),
    path("<str:pk>/add-budget/", AddBudgetView.as_view(), name="add_budget"),
    path("<str:pk>/expenses/", ProjectExpensesView.as_view(), name="expenses"),
    path("<str:pk>/invoices/", ProjectInvoiceView.as_view(), name="invoices"),
    path("<str:pk>/finances/", ProjectFinances.as_view(), name="finances"),
    path("<str:pk>/delete/", ProjectDeleteView.as_view(), name="delete"),
]

urlpatterns += [
    path(
        "customer/modal-create/",
        ModalCustomerCreateView.as_view(),
        name="customer_modal_create",
    ),
]

src/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('src.web.dashboard.urls')),
    path('invoice/', include('src.services.invoice.urls')),
    path('customer/', include('src.services.customer.urls')),
    path('projects/', include('src.services.project.urls')),
    path('quotation/', include('src.services.quotation.urls')),
    path('loans/', include('src.services.loan.urls')),
    path('expense/', include('src.services.expense.urls')),
    path('assets/', include('src.services.assets.urls')),
    path('vendor/', include('src.services.vendor.urls')),
    path('transaction/', include('src.services.transaction.urls')),
    path('charts/', include('src.services.charts.urls')),
    path('accounts/', include('src.web.accounts.urls')),
]

src/services/loan/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.contenttypes.models import ContentType
from django.db import transaction
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, FormView, DeleteView

from src.services.project.bll import (
    add_loan_to_project,
    create_misc_loan,
    return_misc_loan,
)
from src.services.project.bll import return_loan_to_lender
from src.services.project.models import Project
from .forms import LoanForm, MiscLoanForm, MiscLoanReturnForm
from .forms import LoanReturnForm
from .models import Loan, LoanReturn, Lender, MiscLoan
from ..transaction.models import Ledger
from ...web.dashboard.utils import ledger_filter


# VALIDATION ✔
class LendLoanView(LoginRequiredMixin, CreateView):
    """
    Create a loan for a project [( PROJECT LOAN )]
    """

    form_class = LoanForm
    template_name = "loan/lend_loan.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Project, id=self.kwargs["pk"])

    def form_valid(self, form):
        loan = form.save(commit=False)
        lender = form.cleaned_data["lender"]
        amount = form.cleaned_data["loan_amount"]
        reason = form.cleaned_data["reason"]

        # No amount or balance checks needed because a loan is being created.
        if amount <= 0:
            form.add_error("loan_amount", "Amount must be greater than zero.")
            return self.form_invalid(form)
        loan.project = self.get_object()
        loan.save()

        # Make changes to the Project & Ledger before creating the loan Object
        add_loan_to_project(
            project_id=self.kwargs["pk"], amount=amount, source=loan, reason=reason
        )

        # Link the project to loan object

        messages.success(
            self.request,
            f"Loan of {amount} successfully created for project {self.get_object().project_name}.",
        )
        return redirect("project:detail", pk=self.kwargs["pk"])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project"] = self.get_object()  # For The GoBack Button (PK)
        return context


class LoanListView(LoginRequiredMixin, ListView):
    model = Loan
    template_name = "loan/loan_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["project"] = get_object_or_404(Project, id=self.kwargs["pk"])
        return context

    def get_queryset(self):
        return Loan.objects.filter(project=self.kwargs["pk"]).order_by("-due_date")


# VALIDATION ✔
class ReturnLoanView(LoginRequiredMixin, CreateView):
    form_class = LoanReturnForm
    template_name = "loan/return_loan.html"

    def get_object(self, queryset=None):
        return get_object_or_404(Loan, id=self.kwargs["pk"])

    def form_valid(self, form):
        return_amount = form.cleaned_data["return_amount"]
        remarks = form.cleaned_data["remarks"]
        loan = self.get_object()

        loan_return = form.save(commit=False)

        # Validate the Form:

        if return_amount <= 0:
            form.add_error("return_amount", "Amount must be greater than zero.")
            return self.form_invalid(form)

        if return_amount > loan.remaining_amount:
            form.add_error(
                "return_amount", "The amount is more than the project loan amount."
            )
            return self.form_invalid(form)

        if return_amount > loan.project.project_account_balance:
            form.add_error(
                "return_amount", "The amount is more than Project account balance."
            )
            return self.form_invalid(form)

        # Create an expense Object for this project & Perform the return.
        return_loan_to_lender(
            project_id=loan.project.id,
            loan_id=loan.pk,
            amount=return_amount,
            reason=remarks,
        )

        loan_return.loan = loan
        loan_return.save()
        messages.success(
            self.request,
            f"Successfully recorded loan return of {return_amount} for "
            f"project {loan.project.project_name}.",
        )
        return redirect("project:detail", pk=loan.project.id)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loan = self.get_object()
        logs = Ledger.objects.filter(
            project=loan.project, transaction_type="RETURN_LOAN"
        )
        context["loan"] = loan
        context["project"] = loan.project
        context["return_logs"] = logs
        return context


class LenderListView(LoginRequiredMixin, ListView):
    model = Lender
    paginate_by = 25


class LenderDetailView(LoginRequiredMixin, DetailView):
    model = Lender

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        loans = self.object.loans.all()
        misc_loans = self.object.misc_loans.all()

        combined_loans = list(loans) + list(misc_loans)

        context["loans"] = combined_loans
        return context


class LenderCreateView(LoginRequiredMixin, CreateView):
    model = Lender
    fields = "__all__"
    success_url = reverse_lazy("loan:lenders")


# VALIDATION ✔
class MiscLoanCreateView(LoginRequiredMixin, CreateView):
    model = MiscLoan
    form_class = MiscLoanForm
    success_url = reverse_lazy("loan:lenders")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["lender"] = get_object_or_404(Lender, pk=self.kwargs["pk"])
        return context

    def form_valid(self, form):

        with transaction.atomic():
            misc_loan = form.save(commit=False)
            destination_account = form.cleaned_data["destination"]
            reason = form.cleaned_data["reason"]
            amount = form.cleaned_data["loan_amount"]

            if amount <= 0:
                form.add_error("loan_amount", "Amount must be greater than zero.")
                return self.form_invalid(form)
            misc_loan.save()

            success, message = create_misc_loan(
                destination_account=destination_account,
                misc_loan_pk=misc_loan.pk,
                reason=reason,
                amount=amount,
            )

        messages.success(self.request, f"Loan of amount {amount} created successfully")
        return super().form_valid(form)


class MiscLoanReturnView(LoginRequiredMixin, FormView):
    form_class = MiscLoanReturnForm
    template_name = "loan/misc_loan_return.html"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.object = None

    def dispatch(self, request, *args, **kwargs):
        self.object = get_object_or_404(MiscLoan, id=self.kwargs["pk"])
        return super().dispatch(request, *args, **kwargs)

    def form_valid(self, form):
        return_amount = form.cleaned_data["return_amount"]
        account = form.cleaned_data["source"]
        remarks = form.cleaned_data["remarks"]
        loan = self.object

        if return_amount <= 0:
            form.add_error("return_amount", "Amount must be greater than zero.")
            return self.form_invalid(form)

        if return_amount > loan.remaining_amount:
            form.add_error(
                "return_amount", "The amount is more than the project loan amount."
            )
            return self.form_invalid(form)

        if return_amount > account.balance:
            form.add_error(
                "return_amount", "The amount is more than Project account balance."
            )
            return self.form_invalid(form)

        success, message = return_misc_loan(
            destination_account=self.object,
            source=account,
            reason=remarks,
            amount=return_amount,
        )

        messages.success(self.request, message)
        return redirect("loan:lender-detail", pk=loan.lender.pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        loan = self.object
        context["loan"] = loan
        context["return_logs"] = ledger_filter(
            destination=loan, transaction_type="MISC_LOAN_RETURN"
        )
        return context


class LenderDeleteView(LoginRequiredMixin, DeleteView):
    model = Lender
    success_url = reverse_lazy("loan:lenders")
    template_name = 'loan/lender_confirm_delete.html'

src/services/loan/templates/loan/lend_loan.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Customer{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="page-wrapper">

        <!-- Page Content-->
        <div class="page-content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                            <h4 class="page-title">
                                <a class="btn btn-secondary btn-sm" href="{% url 'loan:list' project.pk %}"><i
                                        class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                                New Loan</h4>

                        </div><!--end page-title-box-->
                    </div><!--end col-->
                </div><!--end row-->

                <div class="row justify-content-center">
                    <h4 class="text-center">Lend loan for Project: <b>{{ project.project_name }}</b></h4>
                    <div class="col-md-12 col-lg-6">
                        <div class="card border-2 shadow-lg">
                            <div class="card-body">
                                <form method="post" class="form">
                                    {% csrf_token %}
                                    {{ form.as_p }}
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                </form>
                            </div><!--end card-body-->
                        </div><!--end card-->
                    </div> <!--end col-->
                </div><!--end row-->
            </div><!-- container -->
        </div>
        <!-- end page content -->
    </div>
{% endblock %}

src/services/loan/templates/loan/lender_confirm_delete.html
{% extends 'dashboard/base.html' %}
{% block title %} Delete {% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


    <div class="page-wrapper">
        <div class="page-content">
            <div class="container-fluid">


                <div class="row justify-content-center mt-3">
                    <div class="col-md-6">
                        <div class="alert alert-danger" role="alert">
                            <strong>Note:</strong> All the objects related to {{ object }} will become NULL.
                        </div>
                        <div class="card shadow-lg">
                            <div class="card-body">
                                <h5 class="ms-2">Are you sure you want to delete "{{ object }}"?</h5>
                                <p class="ms-2 text-danger">This action can not be undone</p>

                                <form method="post">{% csrf_token %}
                                    {{ form }}
                                    <a href="{% url 'loan:lenders' %}">
                                        <div class="btn btn-secondary me-2"><i class="fa fa-arrow-left me-1"></i>Go
                                            Back
                                        </div>
                                    </a>
                                    <input class="btn btn-danger float-end" type="submit" value="Confirm">


                                </form>
                            </div>
                        </div>
                    </div>
                </div>


            </div>
        </div>
    </div>
{% endblock %}

src/services/loan/templates/loan/lender_detail.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Customer{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
    <div class="page-wrapper">
        <div class="page-content">
            <div class="container-fluid">

                <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                    <h4 class="page-title">
                        <a class="btn btn-secondary btn-sm" href="{% url 'loan:lenders' %}"><i
                                class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                        Lender Detail</h4>

                </div>


                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-body">

                                {# IMAGE DIV #}
                                <div class="text-center">
                                    <img style="max-height: 100px" class="rounded-circle"
                                         src="{% static 'img/user-default.jpeg' %}"
                                         height="150px" alt="no-user-image">
                                </div>

                                {# NAME AND OTHER #}
                                <div class="text-center mt-2">
                                    <h5 class="mb-0">
                                        {{ object.name }}
                                        {% if user.is_active %}
                                            <i class="fa fa-check-circle text-success"></i>
                                        {% endif %}
                                    </h5>
                                    <p class="fw-light text-muted mb-0">{{ object.email }}</p>
                                </div>

                                <div class="row mt-4">
                                    <div class="col">
                                        <p class="mb-0 text-center h5"><i class="fa fa-phone me-1"></i>Phone</p>
                                        <p class="mb-0 text-center">{{ object.phone }}</p>
                                    </div>
                                    <div class="col text-center">
                                        <p class="mb-0 text-center h5"><i class="fa fa-credit-card me-1"></i>IBAN</p>
                                        <p class="mb-0 text-center">{{ object.iban }}</p>
                                    </div>
                                    <div class="col text-center">
                                        <p class="mb-0 text-center h5"><i class="fa-solid fa-money-bills me-1"></i>Due
                                            Payments</p>
                                        <p class="mb-0 text-center">{{ object.get_total_due }}.00 PKR</p>
                                    </div>

                                    <div class="col">
                                        <p class="mb-0 text-center h5"><i
                                                class="fa-solid fa-envelope-open-text me-1"></i>Account Number
                                        </p>
                                        <p class="mb-0 text-center">{{ object.account_number }}</p>
                                    </div>

                                    <div class="col">
                                        <p class="mb-0 text-center h5"><i
                                                class="fa-solid fa-bank me-1"></i>Bank Account</p>
                                        <p class="mb-0 text-center text-danger">
                                            {{ object.bank_account }}
                                        </p>
                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

                {# STATISTICS #}
                <div class="row">
                    <div class="col-md-12">
                        <div class="card">
                            <div class="card-header">
                                <div class="row align-items-center">
                                    <div class="col">
                                        <h4 class="card-title">All Loans
                                            <a href="{% url 'loan:lend-misc-loan' lender.pk %}">
                                                <div class="btn btn-success float-end"><i class="fas fa-plus"></i>
                                                    Create Loan
                                                </div>
                                            </a>
                                        </h4>
                                    </div><!--end col-->
                                </div>  <!--end row-->
                            </div><!--end card-header-->
                            <div class="card-body pt-0">
                                <div class="table-responsive">
                                    <table class="table table-bordered mb-0 table-centered">
                                        <thead>
                                        <tr>
                                            <th>Project</th>
                                            <th>Total Amount</th>
                                            <th>Remaining</th>
                                            <th>Due Date</th>
                                            <th class="text-center">Returned</th>
                                            <th class="text-center">Action</th>
                                        </tr>
                                        </thead>
                                        <tbody>
                                        {% for object in loans %}
                                            <tr>
                                                <td>
                                                    {% if object.project %}
                                                        {{ object.project.project_name }}
                                                    {% else %}
                                                        Not For a Project
                                                    {% endif %}
                                                </td>
                                                <td>{{ object.loan_amount }}</td>
                                                <td>{{ object.remaining_amount }}</td>
                                                <td>{{ object.due_date }}</td>
                                                <td class="text-center {% if object.is_repaid %} text-success {% else %} text-danger {% endif %} ">
                                                    <span><i
                                                            class="fa-solid {% if object.is_repaid %}fa-circle-check {% else %}fa-circle-xmark{% endif %}"></i></span>
                                                </td>
                                                <td class="text-center text-success">
                                                    {% if object.project %}
                                                        <a href="{% url 'loan:return_loan' object.pk %}">
                                                            <i class="fa-solid fa-pen-to-square"></i>
                                                        </a>
                                                    {% else %}
                                                        <a href="{% url 'loan:return-misc-loan' object.pk %}">
                                                            <i class="fa-solid fa-pen-to-square"></i>
                                                        </a>
                                                    {% endif %}
                                                </td>
                                            </tr>
                                        {% endfor %}
                                        </tbody>
                                    </table><!--end /table-->
                                </div><!--end /tableresponsive-->
                            </div><!--end card-body-->
                        </div><!--end card-->
                    </div>
                </div>


            </div>
        </div>
    </div>

{% endblock %}

src/services/loan/templates/loan/lender_form.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Project{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


    <div class="page-wrapper">
    <div class="page-content">
        <div class="container-fluid">


            {% if object %}
                <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                    <h4 class="page-title">
                        <a class="btn btn-secondary btn-sm" href="{% url 'loan:lenders' %}"><i
                                class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                        Edit Lender</h4>

                </div>
            {% else %}
                <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                    <h4 class="page-title">
                        <a class="btn btn-secondary btn-sm" href="{% url 'loan:lenders' %}"><i
                                class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                        Add Lender</h4>

                </div>
            {% endif %}


            <div class="row justify-content-center">
                <div class="col-md-6">
                    <div class="card shadow-sm">
                        <div class="card-header bg-light text-dark text-center">
                            <h5 class="mb-0">Lender Form</h5> <!-- Replace 'Form Title' with your desired heading -->
                        </div>
                        <div class="card-body">
                            <form method="post">
                                {% csrf_token %}
                                {{ form|crispy }}
                                <button type="submit" class="btn btn-primary mt-2">Submit</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock content %}

src/services/loan/templates/loan/loan_list.html
{% extends 'dashboard/base.html' %}
{% block title %}Create Customer{% endblock %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<div class="page-wrapper">
    <div class="page-content">
        <div class="container-fluid">

            <div class="page-title-box d-md-flex justify-content-md-between align-items-center">
                <h4 class="page-title">
                    <a class="btn btn-secondary btn-sm" href="{% url 'project:detail' project.pk %}"><i class="fa fa-arrow-left-long me-1"></i> Go Back</a>
                    Loan Management: {{ project.project_name }}</h4>
                <div class="">
                    <ol class="breadcrumb mb-0">
                        <li class="breadcrumb-item"><a href="{% url 'customer:index' %}">Loan</a>
                        </li><!--end nav-item-->
                        <li class="breadcrumb-item active">Edit</li>
                    </ol>
                </div>
            </div>



            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header">
                            <div class="row align-items-center">
                                <div class="col">
                                    <h4 class="card-title">Project Loans
                                        <a href="{% url 'loan:lend_loan' project.pk %}"><div class="btn btn-success float-end"><i class="fas fa-plus"></i> Create Loan</div></a>
                                    </h4></div><!--end col-->
                            </div>  <!--end row-->
                        </div><!--end card-header-->
                        <div class="card-body pt-0">
                            <div class="table-responsive">
                                <table class="table table-bordered mb-0 table-centered">
                                    <thead>
                                    <tr>
                                        <th>Lender</th>
                                        <th>Total Amount</th>
                                        <th>Remaining</th>
                                        <th>Due Date</th>
                                        <th class="text-center">Returned</th>
                                        <th class="text-center">Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    {% for object in object_list %}
                                    <tr>
                                        <td><a href="{% url 'loan:return_loan' object.pk %}">{{ object.lender.name }}</a></td>
                                        <td>{{ object.loan_amount }}</td>
                                        <td>{{ object.remaining_amount }}</td>
                                        <td>{{ object.due_date }}</td>
                                        <td class="text-center {% if object.is_repaid %} text-success {% else %} text-danger {% endif %} "><span><i class="fa-solid {% if object.is_repaid %}fa-circle-check {% else %}fa-circle-xmark{% endif %}"></i></span></td>
                                        <td class="text-center text-success"><a href="{% url 'loan:return_loan' object.pk %}"><i class="fa-solid fa-pen-to-square"></i></a></td>
                                    </tr>
                                    {% endfor %}
                                    </tbody>
                                </table><!--end /table-->
                            </div><!--end /tableresponsive-->
                        </div><!--end card-body-->
                    </div><!--end card-->
                </div>
            </div>


        </div>
    </div>
</div>


{% endblock %}